on:
 workflow_call:
   inputs:
      message:
        required: true
      message2:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: build dotnet
        run: | 
            echo ${{ github.event.inputs.message }}"
            echo  ${{ github.event.inputs.name }}"

