on:
 workflow_call:
   inputs:
      message:
        type: string
        required: true
      message2:
        type: string
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: build dotnet
        run: | 
            echo ${{ inputs.message }}
            echo ${{ inputs.message2 }}

