name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          source-url: https://nuget.pkg.github.com/mitzenjeremywoo/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Display dotnet version
        run: dotnet --version
    
      - name: build dotnet
        run: | 
            cd $GITHUB_WORKSPACE
            cd src/ConsoleApp1
            dotnet restore
            dotnet build 
            dotnet build --configuration Release 
            #dotnet nuget push /src/ConsoleApp1/bin/Debug/net8.0/*.nupkg
     
      # - name: Test with the dotnet CLI
      #   run: dotnet test
      - name: upload artifacts 
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.dotnet-version }}
          path: ${{ github.workspace  }}/src/ConsoleApp1/ConsoleApp1/bin/Release/net8.0/
        # Use always() to always run this step to publish test results when there are test failures
        #if: ${{ always() }}

      

      